import type { InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Cart from '../cmps/Cart/Cart';
import CheckOut from '../cmps/CheckOut/CheckOut';
import Header from '../cmps/Header/Header';
import Store from '../cmps/Store/Store';
import { onGetItems } from '../features/cart/cartSlice';
import { removeAllItems } from '../utills/utills';
import { useAppDispatch } from '../app/hooks';
const Home: NextPage = ({ products }: any) => {
  const router = useRouter();
  const dispatch = useAppDispatch();

  const checkStatus = async () => {
    if (router.query.status && router.query.status === 'success') {
      await removeAllItems();
      await dispatch(onGetItems);
    }
  };

  useEffect(() => {
    checkStatus();
    // @ts-ignore
  }, [router.query]);

  return (
    <div>
      <Head>
        <title>Next Sports and Camp</title>
        <meta name="description" content="Generated by create Yaniv Shabi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Store products={products} />
        <Cart />
        <CheckOut />
      </main>
      <footer></footer>
    </div>
  );
};

export async function getServerSideProps() {
  // get the current environment
  let dev = process.env.NODE_ENV !== 'production';
  let { DEV_URL, PROD_URL } = process.env;
  // request posts from api
  let response = await fetch(`${dev ? DEV_URL : PROD_URL}/api/products`);
  // let response = await fetch(`http://localhost:3000/api/products`);
  // extract the data
  let data = await response.json();

  return {
    props: {
      products: data,
    },
  };
}

export default Home;
